### ISSUE TITLE
[FEATURE] Can we adjust how many meals we want to eat per day? 

### ISSUE THREAD

**Issue by worldsdream** [alicolville/Weight-Tracker#184]
Can you give us an option, that we can select how many meals a day we want to eat and let us rename them.

For example:

Breakfast
Lunch
Pre-Workout
Post-Workout
Dinner
Before Bed

**Comment by worldsdream** [comment]
Percentages should be adjusted by macros. But there was another thread for it.

**Comment by alicolville** [comment]
Closed this, as I think it is for Meal Tracker.
