### ISSUE TITLE
New shortcode to  display total weight loss between two dates and by group

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#203]

**Comment by jwrigh10** [comment]
This would be a nice feature so when a member of a group logs in, they can see how their group is doing. Can also be used to foster competition between groups!

**Comment by mybestrong** [comment]
Ali!! 😄👍

Rick Wilson
 
Be  Strong UK Ltd
 
www.mybestrong.com

**Comment by alicolville** [comment]
Not likely to implement I'm afriad.
