### ISSUE TITLE
Notify Admin if no weight entry has been made for x days

### ISSUE THREAD

**Issue by jwrigh10** [alicolville/Weight-Tracker#207]
It would be helpful if I was able to set "Notify admin if user has not logged in weight in ____ days". With this feature I can help people be more accountable. Or another idea (Better?) would be for the system to "Send out email to user who has not weighed-in in _____ days". 

The admin could create a custom email (Like in the awards) to be sent out. This would take pressure off of admin as the groups get larger!

**Comment by yekenuk** [comment]
Yeah, I like both ideas! I'll add it in a future release! :)

**Comment by mybestrong** [comment]
I like the notify user idea too :)

**Comment by jwrigh10** [comment]
Would be a great feature. Also, if the administrator could be notified too
so he/she could follow-up that'd be cool too.

Jim

**Comment by alicolville** [comment]
@mybestrong  - conscious this one is pretty old now. Any merit in this?

**Comment by mybestrong** [comment]
Not anymore Ali 😊

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com

**Comment by alicolville** [comment]
Closed because I took far too long ;P

**Comment by mybestrong** [comment]
😂😂❤️

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com
