### ISSUE TITLE
Separate User section in three sections

### ISSUE THREAD

**Issue by burggraaf** [alicolville/Weight-Tracker#219]
It would be great if the user settings could be implemented separately with a shortcode or shortcode attribute; User Data (gender, height, etc), User preferences (kg or pounds, etc) and Delete data. 

Example: I don't need the users to change their 'User preferences', because they're all Dutch and are using the same preferences. Next to that I prefer to show the data deletion button on a less prominent place.

_Note: This issue is a bit similar to: https://github.com/yekenuk/Weight-Loss-Tracker/issues/189, but since that issue is only about the Delete data function, I have added it as a new issue._

**Comment by alicolville** [comment]
Not likely to implement I'm afriad.
