### ISSUE TITLE
Add prompt if entering entry for same date

### ISSUE THREAD

**Issue by alicolville** [alicolville/Weight-Tracker#226]
As per:
https://wordpress.org/support/topic/add-entry-ux/

> When a user adds a new entry that has the same date as a previous entry, the default behavior is it overwrites the previous entry. Is there a way to add a popup dialogue box asking if the user wants to overwrite the previous entry or edit/change the date of the current entry?
> 
> We are having several users accidentally add an entry with the same dates as previous entry’s and they lose everything from that entry without even realizing it.
> 
> This will make this very useful plugin more user resilient!
> 
> Thank you.

**Comment by PascalPoeck** [comment]
I confirm that this is confusing everybody. They need to upload 3 pictures regarding "my needs" and first they need to add a new weight for each picture (why???) and then do that 3 days in a row... Really anoying ^^

**Comment by alicolville** [comment]
Out in 9.0
