### ISSUE TITLE
"Calories to subtract" change on percent

### ISSUE THREAD

**Issue by budsvuj** [alicolville/Weight-Tracker#245]
Hi
I have problem with function  "Calories to subtract". Now it is firmly value set example on 600kcal. But for reduce weight is good set "Calories to subtract" minus 10-15%. Now it is impossible, because i can set only firmly value. You can add second option for "Calories to subtract", but in percent.
Example 
I set "Calories to subtract" on 10%
Woman
Daily calorie needs = 1600kcal and quantity calories for reduce will be 1600- ((1600/100)*10) = 1440Kcal

Man
Daily calorie needs = 2600kcal and quantity calories for reduce will be 2600- ((2600/100)*10) = 2340Kcal

Thank you for cooperative

**Comment by alicolville** [comment]
Will be in 7.6.8
