### ISSUE TITLE
Challenge Data Calculations

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#247]
Total weight loss is calculated as is - thats fine 🙂

Average weight loss to disregard those members who only recorded a single weight.

The rationale is we have a lot of members who sign up on a free trial, record a weight as part of the onboarding but then leave, and never record another weight with us

Average BMI change to disregard those members who only recorded a single weight.

% bodyweight to disregard those members who only recorded a single weight.   

Or, if its easier - disregard those with a single weight entry for the period from the reports?

**Comment by yekenuk** [comment]
Will be in 7.5.2
