### ISSUE TITLE
Challenge Data Results Anomaly

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#249]
See the following challenge: -

https://mybestrong.com/wp-admin/admin.php?mode=view&challenge-id=9&page=ws-ls-challenges&filter-gender=0&filter-age-range=0&filter-group-id=9&filter-opt-in=0

Filters: -

Gender: blank
Age range: Blank
Group: None selected
Opted in: Everyone

1. Sort by weight loss
2. Navigate to page 81 of the data

There are 16 pages of data (81-97) that aren't correctly sorted

**Comment by alicolville** [comment]
Will add a new Challenge filter "Min. Weight Entries".

This will default to "Two or more" i.e. ignore all entries that have only entered one weight.

Will be in 7.6
