### ISSUE TITLE
Challenge Feature: Awards & Group

### ISSUE THREAD

**Issue by jwrigh10** [alicolville/Weight-Tracker#253]
Ability to have user awards added for:
# days of Weight Tracker Streaks
# days of Meal Tracker Streaks
An "Award" for Challenge Completion

Regarding the Challenge Groups

- Shortcode to identify which Challenge the user is participating in addition to shortcode for the Group. For example, you have member of the "Online Group" who joins a challenge the system could show they are in Group: Online Members and Challenge: March Madness.

**Comment by alicolville** [comment]
Not likely to implement I'm afriad.
