### ISSUE TITLE
increase number of letters in custom fields weight tracker

### ISSUE THREAD

**Issue by jarocs** [alicolville/Weight-Tracker#300]
" weight tracker " plugin, i renew my pro version for another year, im so happy, working well and i have question.

in " custom fields " its very low limit of letters, i need little bit more to put there whole question
lets say i can not "ask" people there 

"how much fluid do you consume daily"

because its " to much " letters

i have to write something like "  how much fluid daily " or something like this, not everyone understand that, and its looks not so good .

it is possible to change that limit ?

thanks
Damian

**Comment by alicolville** [comment]
Released. 8.1.4
