### ISSUE TITLE
Be able to change the “Additional fields” label on the chart

### ISSUE THREAD

**Issue by thomarto** [alicolville/Weight-Tracker#301]
When it comes to Weight Tracker's chart I will only ever be displaying two other data points along with weight – i.e. body fat and visceral fat. It would be great if I could edit the "Additional field" label accordingly to make it more descriptive for my clients.

<img width="692" alt="additional fields" src="https://user-images.githubusercontent.com/26119379/95563267-18b46a80-0a15-11eb-9572-e07467c67374.png">

**Comment by alicolville** [comment]
This isn't something I would change in the plugin - otherwise I'd have to add settings for all fields.

Instead, install a plugin like the following, and for the given language change the text string:

https://en-gb.wordpress.org/plugins/loco-translate/
