### ISSUE TITLE
See a list of all users who have submitted a weight entry

### ISSUE THREAD

**Issue by thomarto** [alicolville/Weight-Tracker#302]
In Weight Tracker > Manage User Data there is a Top 10 league table and a list of the last 100 entries. It would also be great if I could also see a list of all users who have submitted a weight entry. So something similar to the last 100 entries, but it’s a list of all users showing their most recent entry.

**Comment by alicolville** [comment]
If I'm honest, I don't think this will make sense to my core users - in the sense I've not had requests for it, nor do I see it being of big benefit. But I'll leave the ticket open for a while to see if anyone else voices an opinion.
