### ISSUE TITLE
Ability to hide the Overview tab in [wt]

### ISSUE THREAD

**Issue by thomarto** [alicolville/Weight-Tracker#303]
I’m intending to breakout everything from the Overview tab into its own section using the available shortcodes: i.e. the chart, setting a target and adding an entry. In this scenario the Overview tab in the main [wt] shortcode becomes redundant, but I’d still like to show my clients the History, Photos and Preferences tabs (I’m already hiding the Advanced tab).

**Comment by alicolville** [comment]
The Overview tab can't be removed easily as other tabs (like all data and settings) redirect to it or load data into it. 

As each element of the main shortcode can be built from individual ones, I'd recommend using them.
