### ISSUE TITLE
Display Stones & lbs on the chart

### ISSUE THREAD

**Issue by thomarto** [alicolville/Weight-Tracker#304]
A couple of my clients have complained that even though they’ve chosen _Stones & lbs_ in Preferences, the chart shows lbs. 

**I totally understand why it does this!**

But I was also wondering if there was some kind of trickery that could show the **_labels_** in St&lbs while in the background the chart is just plotting the numbers associated with lbs.

(I fully appreciate that this one it feels like I’m asking you to do magic!)

**Comment by alicolville** [comment]
I'm afraid this isn't possible.
