### ISSUE TITLE
Challenges Table

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#353]
Ali - as discussed. Could the challenges table on the front end maintain state to display sorting options when on mobile?

**Comment by alicolville** [comment]
Closed for now.

**Comment by mybestrong** [comment]
Hi Ali,

Here's an example..

https://mybestrong.com/rick-test/

On the desktop view you can sort on all columns as below..

![image](https://user-images.githubusercontent.com/44278135/145028351-b5ec2e48-01ba-4831-93d9-cac896bc1720.png)

![image](https://user-images.githubusercontent.com/44278135/145028420-965373dc-000c-451c-8b23-feca6297ac15.png)

![image](https://user-images.githubusercontent.com/44278135/145028452-b1545158-9745-4e8b-8e00-470c27b1d301.png)

![image](https://user-images.githubusercontent.com/44278135/145028486-28b7bd83-cdee-464a-9673-957ec5c346aa.png)

On mobile view you can only sort by first name...

![image](https://user-images.githubusercontent.com/44278135/145028578-3391470f-6f01-4100-a79b-14bca23606e3.png)

Is it possible to sort by each column in mobile view?
