### ISSUE TITLE
Custom Field Charts when no data

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#367]
![image](https://user-images.githubusercontent.com/44278135/122917019-77c4d000-d355-11eb-9480-0ab4057665ae.png)

No charts if no data and the message-no-data argument doesn't work

**Comment by alicolville** [comment]
Fixed.

**Comment by mybestrong** [comment]
Busy boy x

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com
