### ISSUE TITLE
Error in CSS

### ISSUE THREAD

**Issue by shakethatweight-simon** [alicolville/Weight-Tracker#386]
https://github.com/alicolville/Weight-Tracker/blob/master/assets/css/ws-ls.css#L275-L277

```
.ws-ls-user-data-ajax th, td {
  font-size: 13px;
}
```

With this style all `td` elements on the site are set to 13px instead of just the cells in the weight tracker that you were trying to target.

Proposed solution:

```
.ws-ls-user-data-ajax th, .ws-ls-user-data-ajax td {
  font-size: 13px;
}
```

ws-ls.min.css should also be updated

**Comment by alicolville** [comment]
Ah thank you! I'll put in 9.2 :)
