### ISSUE TITLE
Notes Enhancements

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#393]
Firstly I love this Ali! 

Feedback from me as discussed: -

1. Add the ability to send a global note based on user role
2. Add the ability to use Shortcode Variables in messages
3. Add max number of notes to return in shortcode
4. Add pagination option to shortcode
5. Add first name to email generated

**Email Apostrophe Issue**

Hello,

A new note has been sent to you from Be Strong:

Don\'t forget to check out today\'s W.O.W!

**Comment by alicolville** [comment]
Apostrophe issue will be fixed in 9.3.1

**Comment by alicolville** [comment]
Done: Added limited support for shortcodes within notes

**Comment by alicolville** [comment]
Done: Added support for {first-name} / { last-name} within email template.

**Comment by alicolville** [comment]
Paging added in a previous release. See: [notes-per-page ](https://docs.yeken.uk/shortcodes/wt-notes.html)

**Comment by mybestrong** [comment]
Loving all these updates ❤️❤️❤️

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com

**Comment by alicolville** [comment]
Done, except for the following. I think I'd prefer that was done in another plugin :)

```
Add the ability to send a global note based on user role
```

**Comment by mybestrong** [comment]
Great idea Ali 😊👏

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com

**Comment by mybestrong** [comment]
> Done, except for the following. I think I'd prefer that was done in another plugin :)
> 
> ```
> Add the ability to send a global note based on user role
> ```

If you create another plugin consider integrations to all the major membership plugins and add the ability to send to users by membership group. They have millions of users between them and as far as I'm aware none have the global notes option.

I have woocommerce memberships if you need a copy.

https://woocommerce.com/products/woocommerce-memberships/
https://memberpress.com/
https://www.paidmembershipspro.com/
https://restrictcontentpro.com/
https://ultimatemember.com/

**Comment by alicolville** [comment]
Kickstarter me time ha.
