### ISSUE TITLE
Feature Request - % of Calories Shortcode

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#397]
Ali!

There are loads of instances where we have to display a percentage of the data created by WT.

We're using this https://wordpress.org/plugins/calculate-values-with-shortcodes/ which hasnt been updated in ages - it generates errors and will likely soon fall over

We LOVE this..

[wlt-calories progress="gain" type="total"]

..but this would be awesome

[wlt-calories progress="gain" type="total" %="30"]

Love you loads 😊 x

**Comment by alicolville** [comment]
Ha.

So in that example you want to be able to display 30% of the total?

**Comment by mybestrong** [comment]
Yep ❤️🙏

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com

**Comment by alicolville** [comment]
This is in 9.3.6 :)
