### ISSUE TITLE
Quick Weight Entry Addon Email

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#398]
Hi Ali,

Seems to be an issue with the email generated to the user on the quick weight entry add on relating to the target weight..

Today's Weight **11st 6lbs**
You currently weight **11st 6lbs.**
The difference between your current weight and your last recorded weight is -6lbs.
Start Weight 12st 1lbs
You started your Be Strong journey with a recorded weight of 12st 1lbs.
Difference -9lbs
The difference between your starting weight and current weight is -9lbs.
Target Weight **9st 6lbs**
The target weight you have set for yourself is **9st 6lbs.**
Distance from Target Weight **+8.75lbs**
You are currently **+8.75lbs** away from achieving it.

**Comment by alicolville** [comment]
This is actually an issue with your enhanced plugin. As the main plugin has moved on your older one hasn't.

Fix here: https://github.com/alicolville/wlt-be-strong/releases/tag/1.0.3

**Comment by mybestrong** [comment]
Hi Ali!

Installed 1.0.3 from that link but it did actually replace 1.0.5 and the quick weight entry section isn't available now.

Sorry to be a pain!

**Comment by mybestrong** [comment]
[wlt-be-strong-1.0.5.zip](https://github.com/alicolville/Weight-Tracker/files/7668803/wlt-be-strong-1.0.5.zip)

This was the version we had :)
