### ISSUE TITLE
Custom Field Forms

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#400]
Hi Ali,

**This works perfectly..**

https://mybestrong.com/steps-tracker/

1 x number field

**This doesn't hold the data you enter but for the ones it has recorded data the table seems to render ok on desktop and mobile..**

https://mybestrong.com/progress-tracker/

2 x large text fields and a range slider

**This doesn't hold any data that you enter and the table is not rendered correctly on either desktop or mobile..**

4 x large text fields and 2 x small text fields

https://mybestrong.com/goal-tracker/

**Comment by alicolville** [comment]
This one still an issue?

**Comment by mybestrong** [comment]
Not now Ali - your latest fix sorted it!

**Comment by alicolville** [comment]
🥳
