### ISSUE TITLE
Enhancement - Challenges Opt-in Status

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#402]
Ali,

Love the buttons always showing, absolutely perfect!

The icing on the cake would be a shortcode that displays the opt in/out status for the user

[wt-challenges-optin-status]

2 options

You are **opted in** to all challenges on this website
You are **opted out** of all challenges on this website

I'm using a clunky workaround at the moment as per the image below..

![image](https://user-images.githubusercontent.com/44278135/145195975-db128d5f-b64f-4399-8eb4-eca849af81d0.png)

**Comment by mybestrong** [comment]
PS. Hope the do is going well. Remember what I said about the ink ;)

**Comment by alicolville** [comment]
Note to self: Extend [wt-if] for this.

**Comment by alicolville** [comment]
This is in 9.3.6 :)
