### ISSUE TITLE
PHP8 Compatibility - Deprecation notice

### ISSUE THREAD

**Issue by shakethatweight-simon** [alicolville/Weight-Tracker#403]
`Deprecated: Required parameter $array follows optional parameter $prefix in wp-content/plugins/weight-loss-tracker/includes/caching.php on line 273`

https://github.com/alicolville/Weight-Tracker/blob/d4a4a21c260bafeede39eb7c09b250ca978cdf3c/includes/caching.php#L273

Looks like a simple update could be applied:

```
function ws_ls_cache_generate_key_from_array( $prefix = 'wt', $array = []) {
```

**Comment by alicolville** [comment]
Thanks @shakethatweight-simon . Will be in 9.3.5 :)
