### ISSUE TITLE
Additional function in reports

### ISSUE THREAD

**Issue by swinickistroy** [alicolville/Weight-Tracker#409]
Witam serdecznie,
Chciałem wiedzieć, czy planujesz dodać opcję „odpowiadaj na raporty” z wtyczki? W załączniku przesyłam zdjęcie dokładnego miejsca, które mam na myśli. Jeżeli dany klient doda raport, możemy to zobaczyć z poziomu wtyczki, czy planujecie dodać opcję natychmiastowej odpowiedzi na taki raport? A może masz jakieś rozwiązanie?
![111](https://user-images.githubusercontent.com/97556419/149014987-d8d08852-fb2f-415c-8f33-7a2cfb28c080.png)

**Comment by alicolville** [comment]
Hi there,

I could look at adding something there. As in hook into the new notes feature?

Cheers,

Ali

**Comment by swinickistroy** [comment]
yes, it would be a good solution to be able to add responses to reports
from the Panel level. when could improvements be expected?

pt., 14 sty 2022, 11:08 użytkownik Ali Colville ***@***.***>
napisał:

**Comment by alicolville** [comment]
Original comment: Hello and welcome,
I wanted to know if you plan to add the "reply to reports" option from the plugin? Attached I am sending you a photo of the exact place I mean. If a given client adds a report, we can see it from the plug-in level, do you plan to add an option for immediate response to such a report? Or maybe you have some solution?
