### ISSUE TITLE
Challenges Table Not Updating In Real Time

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#411]
When I first set it up it logged nothing in the challenge table for the first two weeks. 

I then created a new challenge and it populated all the data in the table for the period. It's stuck again now which suggests it's only creating the table when ran - more like a one time report xx

Demo: https://mybestrong.com/2021/12/08/january-leaderboard-challenge/

**Comment by alicolville** [comment]
Fix going out in 9.3.8. Should say, challenge data will only be refreshed hourly (saves intensive load).

**Comment by mybestrong** [comment]
You star! Got you some poss homers from a friend of mine too 😊👍

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com
