### ISSUE TITLE
Dedicated BMI Calculator

### ISSUE THREAD

**Issue by alicolville** [alicolville/Weight-Tracker#415]
As per original request:

> As you know, for adults - you don’t need DOB or sex – but you do need to be able to switch between imperial and metric

> https://www.nhs.uk/live-well/healthy-weight/bmi-calculator/

> https://25bmi.com/bmi-calculator/

> You get a single number – 30.5 – then placing that number within the BMI bands is what is useful to the user.  The NHS do a good job of this.

**Comment by mybestrong** [comment]
I love the NHS example x

**Comment by sbservices** [comment]
Love the NHS example as well.  My 2 clients have both asked for a BMI calculator page, so it can be used as a tool to encourage visitors to subscribe as a member and join the group.  So I have done a basic one as example here
https://weighlesswonders.ie/bmi-calculator/
which shows the visitor that if their BMI is overweight, a button appears to ask them to join now.
So I'd like to be notified if you do create this as either part of the current plugin in the pro features.
Currently I'm using Calculated Field Forms to generate this, but I haven't been able to do a 'm & cm to ft & in' switch button.

**Comment by alicolville** [comment]
Hi folks,

I've released a simple one:

`[wt-bmi-calculator`

https://github.com/alicolville/Weight-Tracker/releases/tag/10.1

Ali
