### ISSUE TITLE
Hip2Waist Caclulator

### ISSUE THREAD

**Issue by alicolville** [alicolville/Weight-Tracker#416]
Build in a hip2waist calculator.

**Comment by alicolville** [comment]
https://www.healthline.com/health/waist-to-hip-ratio#:~:text=Calculate%20your%20WHR%20by%20dividing%20your%20waist%20circumference%20by%20your%20hip%20circumference

**Comment by YOPT21** [comment]
Any news on this ?

**Comment by alicolville** [comment]
Not yet. Hopefully once the beta has been signed off I'll use that UI kit to build these things out.

**Comment by YOPT21** [comment]
Hey Ali, this was the original thread for the hip to waist stuff.

**Comment by alicolville** [comment]
Will be in 10.3 ;)

**Comment by alicolville** [comment]
Done, will be in 10.3.
