### ISSUE TITLE
Enhancement Request - Add Firstname & Lastname to Search

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#423]
When we search for a user, we would search by their name as we wouldn’t know their username or email.  Some user accounts get created with their nickname as their display name, which means they don't appear when searching for the persons Firstname.

Could this be something considered as an enhancement.

Many thanks
Zoe Sterling

**Comment by sbservices** [comment]
Thanks a mill 😊

**Comment by alicolville** [comment]
This will be covered in your custom work :)
