### ISSUE TITLE
Have Stones & Pounds become default if you change your default settings to St & lbs

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#432]
We have the defaults set at Stones and Pounds but when you go to open a new customer and add their details, the default is set to kg in the drop down box.

here is the settings page screenshot

https://snipboard.io/r7qE4i.jpg

here is the user details page I refer to

https://snipboard.io/1CjyUO.jpg

I would expect all system defaults to change to Stones and Pounds if the main settings are set at stones and pounds

**Comment by alicolville** [comment]
Fixed in 10.0.4.
