### ISSUE TITLE
Add more admin changeable default settings

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#433]
In general it would be useful to be able to set your preferred defaults for all new customers to those that you would use most frequently for your customer base. e.g. if the majority of your customers want to 'lose weight' then rather than have to change this for each new customer you add to the system, if we could set defaults for adding new customers by way of a preferred defaults that would be great.

https://snipboard.io/UzX2Yi.jpg

**Comment by alicolville** [comment]
I think this has now been done.
