### ISSUE TITLE
Add Additional users as "Coaches" with restricted access to weight tracker only

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#436]
It would be very useful to be able to create a new user with access level of 'coach' and all they can see is the weight tracker for logging the weights of the customers that week.  Currently for a temp coach to cover a class, they have to login to to wordpress as an administrator which means they can see all sales data in woocommerce and they have access to everything.

Perhaps this can be achieved by other plugins for user permissions instead? If so, do you have any recommendations for which plugin?

**Comment by alicolville** [comment]
This isn't as granular, but the following, existing setting, does this to a degree:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/10127199/163544422-2be1cc1b-8ee4-455b-89d9-d136dc67dacb.png">

**Comment by sbservices** [comment]
Thanks, I think this may do the job. 😊
