### ISSUE TITLE
Reporting - Weight Loss for a Group for Date Range

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#438]
To be able to export a report to get a total weight loss for a group for the week as a total. 

We can see in this quick view gives us ‘forever’ since day 1 for each group.
https://snipboard.io/vxdJa6.jpg

In weight loss classes at the start of the talk (for those who stay!), the coach would write on the board the groups total weight loss for the week as a conversation starter to see who contributed to the results and who didn't (if they want to share of course). So it would be useful to be able to grab a total after she has finished weighing everyone in a summary screen for the group.

**Comment by alicolville** [comment]
Good idea ;)

**Comment by sbservices** [comment]
Hi
Just asking for a follow up on this one, to see if there is any timescale on implementation on this please?
