### ISSUE TITLE
BFI - Body Fat Index

### ISSUE THREAD

**Issue by Jfhealthysolutions** [alicolville/Weight-Tracker#446]
Body Fat Index (BFI) Congratulations for the version 10 interface 👏🏻 but I have 2 suggestions:
 1. Show the current BMI in “Home” and 
 2. It would be great if you could add the Body Fat Index to the system… My clinic need this urgently!
 
 Thnaks 🙏

**Comment by alicolville** [comment]
Thanks for the reply. 

I'm thinking of making the boxes customisable per tab. So you can specify which ones appear and in which order on each tab.

As for body fat index, that is potentially a feature I could add in another release (it maybe worth you adding that as a separate feature request).

**Comment by alicolville** [comment]
New ticket added for summary boxes #448

**Comment by alicolville** [comment]
@Jfhealthysolutions , you can now specify which boxes and the order they appear at the top of the tabs in 10.0.2:

https://github.com/alicolville/Weight-Tracker/releases/tag/10.0.2

**Comment by Jfhealthysolutions** [comment]
Awesome!! I’ll try in few minutes. Thanks 🙏

**Comment by Jfhealthysolutions** [comment]
Awesome!! Thank you for everything

**Comment by Jfhealthysolutions** [comment]
I'm trying to configure the boxes but I don't know where it is. Can you
tell me where I can do it? Thank you

**Comment by alicolville** [comment]
If you look here:

https://docs.yeken.uk/shortcodes/wt-beta.html

Then look at the arguments summary-boxes-* ;)
