### ISSUE TITLE
[wt-beta]

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#447]
So just quick browse through atm. Noticed that the title for the format to record the weight doesn't line up with the drop down box to record. So far loving it tho! 
!
[16539394614862526510384718597281](https://user-images.githubusercontent.com/82499071/171051544-6e03e3e6-fd9a-479a-ba28-9016cd59a0a5.jpg)

**Comment by alicolville** [comment]
Oh, that maybe theme related. What Theme do you use?

**Comment by YOPT21** [comment]
That issue has suddenly disappeared,  now I have a fresh look and it is looking incredible. Will continue to test

**Comment by YOPT21** [comment]
All good now
