### ISSUE TITLE
Scheduled Weigh In reminder 

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#453]
Being able to remind clients to input their weight either on a weekly or a monthly rather than daily could be beneficial.

**Comment by alicolville** [comment]
Is this to expand https://docs.yeken.uk/shortcodes/wt-reminder.html?

**Comment by YOPT21** [comment]
Exactly

**Comment by alicolville** [comment]
Closed as a duplicate of #268
