### ISSUE TITLE
Customize font in Beta Weighttracker and Mealtracker shortcode not showing properly inside a tab or Accordian

### ISSUE THREAD

**Issue by LhowellAZ** [alicolville/Weight-Tracker#455]
HI Ali, the new beta WT works well, except that it didn't pick up on my theme fonts.  Can you help with that?
Also, I'd love to tuck the Meal Tracker into an Accordian or Tab, but it doesn't render correctly.  Anything to do about that?

https://www.loom.com/share/d691275b152b4c6faf7ad01e600ab7f9

**Comment by alicolville** [comment]
Hi there,

Ah yes, I'll add something in around the font :)

As for Meal Tracker, that would need further investigation. For some reason, it looks like the CSS/JS isn't being included properly for the plugin which I'm presuming is down to the accordion (perhaps because it's closed at the start). Could you look at your browser dev tools to see if there are any errors being thrown?

Cheers,

Ali

**Comment by LhowellAZ** [comment]
Ok…what would be ETA on font update?

And, as for Mealtracker, I removed it for now from My Member Dashboard page as in the video, but here is a private page where I demo  placement of [mealtracker] in both an accordian and a page switcher.
As you can see, Weight Tracker shows perfectly, but MealTracker doesn’t… I really want to have these on the same page, under tab, or accordian or switcher, to minimize new page openings…

https://theforceforhealth.com/my-healthtrackers/

And I’m sorry…not sure what you want me to look at when you say “dev tools and errors being thrown?”
If you give me a video, or you can log into my admin and check

https://theforceforhealth.com/wp-admin/
***@***.******@***.***>
LH2022!!!!!

Does anybody else have this issue?





‌
[signature_804444520]
[signature_2514632619]
[facebook]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_TheForceforHealth_&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=hWOjJXeywz2gfZAyuZ8kYM0HiybI9VxklLESPoxEF4d_emJvPFzBqrLYJC-kIf67&m=lVdagMzbTbWDHzC47FqHFjPqGSOcnYnkYMuPMHezCOQ&s=gh57nsjNXFSCoahg0rbVJmjksghaFcAU7oHxYuIfiAQ&e=>
[twitter]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_ForceforHealth&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=hWOjJXeywz2gfZAyuZ8kYM0HiybI9VxklLESPoxEF4d_emJvPFzBqrLYJC-kIf67&m=lVdagMzbTbWDHzC47FqHFjPqGSOcnYnkYMuPMHezCOQ&s=ZFhKqAdNjzQqGgz0uJ03p8hQBx86GVdKl6x6nYHQJpQ&e=>
[linkedin]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company_theforceforhealth&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=hWOjJXeywz2gfZAyuZ8kYM0HiybI9VxklLESPoxEF4d_emJvPFzBqrLYJC-kIf67&m=lVdagMzbTbWDHzC47FqHFjPqGSOcnYnkYMuPMHezCOQ&s=1051RVAFUss0P9mizeFS_182e3vGXzxkWK3N6R130Ow&e=>
Lucy  Howell
CEO, co-founder
The Force for Health® Network

[signature_4109399832]
(833) 693-6723<tel:(833)%20693-6723> | 520 878 6683<tel:520%20878%206683>
[signature_627015654]
***@***.******@***.***>
[signature_2624487022]
www.theforceforhealth.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.theforceforhealth.com_&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=hWOjJXeywz2gfZAyuZ8kYM0HiybI9VxklLESPoxEF4d_emJvPFzBqrLYJC-kIf67&m=lVdagMzbTbWDHzC47FqHFjPqGSOcnYnkYMuPMHezCOQ&s=2yUnhvUbnFe337Jy1jdtbddw3-tz8hP3Bmk9JkSXs6M&e=>





From: Ali Colville ***@***.***>
Date: Thursday, June 2, 2022 at 3:02 AM
To: alicolville/Weight-Tracker ***@***.***>
Cc: Lucy Howell ***@***.***>, Author ***@***.***>
Subject: Re: [alicolville/Weight-Tracker] Customize font in Beta Weighttracker and Mealtracker shortcode not showing properly inside a tab or Accordian (Issue #455)

Hi there,

Ah yes, I'll add something in around the font :)

As for Meal Tracker, that would need further investigation. For some reason, it looks like the CSS/JS isn't being included properly for the plugin which I'm presuming is down to the accordion (perhaps because it's closed at the start). Could you look at your browser dev tools to see if there are any errors being thrown?

Cheers,

Ali

**Comment by alicolville** [comment]
Hi,

10.0.3 will go out over the next few days and will include this new argument:

`[wt-beta disable-main-font=true]`

As for the Meal Tracker, unfortunately, that wasn't designed or tested to be within an accordion and would require additional development work.

Cheers,

Ali

**Comment by alicolville** [comment]
10.0.3 deployed :)
