### ISSUE TITLE
Add links and format text for notes section

### ISSUE THREAD

**Issue by Geroimparable** [alicolville/Weight-Tracker#460]
Would be helpful if we can add links, format the text with a text editor, in the notes section. Thanks

**Comment by alicolville** [comment]
Is this a new feature so you can add richer text? Or, has something broken? :)

**Comment by Geroimparable** [comment]
Well this and that :) before when i tricked this and add some link with
html, in the front end the link was showing fine, but now no. Anyways was
kind of difficult to everytime add a link writing html. Would be nice to
add a link fast or richer text with a text editor in the box of the notes,
thanks mate!

**Comment by alicolville** [comment]
Ah ok, where is the link not showing correctly? In the new [wt-beta] shortcode? Could you dump some example HTML here and I can test?

**Comment by alicolville** [comment]
Fixed in https://github.com/alicolville/Weight-Tracker/releases/tag/10.1.1

**Comment by Geroimparable** [comment]
AMAZING!!! works like a charm!

THANK YOU SO SO MUCH. I will be more active on github

APPRECIATE!

**Comment by alicolville** [comment]
Feel free to review ;)

https://wordpress.org/plugins/weight-loss-tracker/#reviews

**Comment by Geroimparable** [comment]
Also i recorded a video with some feedback about how everything is running
on my side :
https://drive.google.com/file/d/1YdEbp-Bw3xh73hKsIVTD_XbdME1m5z0B/view?usp=drivesdk

Thank you so much
