### ISSUE TITLE
Enhancement Request: Total Losses & Total Gains

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#462]
Is it possible to include the totals for losses and gains as well as a total between losses and gains for groups?

So the total lost in one column, total gains in second column and the third column would be the total of the losses and the gains?

<img width="976" alt="losses and gains" src="https://user-images.githubusercontent.com/101115016/172858499-7379a6b5-cb9d-4565-808e-b62c4784f153.png">
?

This is helpful when you've finished weighing everyone in and you want to tell your group how much they've lost this week.  Because it adds the losses and gains together, when you get someone coming back to the class that hasn't been in a long time and they've gained 3st for example, it spoils the totals!  Even though its correct!

How the customers are using this currently is by regenerating the stats after they've finished the weigh ins and they're calculating the totals for that session based on what it was and what it is after regenerating stats for the group. (Great use of the features already there!).

Thanks for the consideration.

**Comment by YOPT21** [comment]
Excited to for this to come through. Will be following

**Comment by alicolville** [comment]
On this, do you mean, say for loss, work out which members in a group have overall lost weight and total? Then do the same for gain?

**Comment by sbservices** [comment]
Yes, so you can see total gains in a group separate to the losses and then the difference. i.e. Class had 20 members through and say 12 lost weight and 8 had a gain, there would be a total for all the losses and a total for all the gains, then a difference between the two totals overall, either adding the gains to the losses or taking the gains away from the total losses.  This is the same for the 'End of Class Reporting'.
Because it only takes one person that hasn't been for years to turn up with 5st on and the total for the class can appear as though no body lost any weight that week!!  So 19 out of 20 could have lost 1lb each and then 1 returning member adds 70lb to the -19lb, giving the class an overall gain of 51lb. You couldn't be broadcasting that as a WIN to the group!  So it is good to identify the gains and the losses separately in both reports. The weight loss coach can then identify the 'losses' for celebrating without highlighting that the figures this week were spoilt by 1 member gaining 5st !!  Not very welcoming for the returnee either!!

**Comment by sbservices** [comment]
Cheers!  I didn’t want it to go on the project work, unless you had time, so it could get done as part of another project if not.

**Comment by mybestrong** [comment]
> 

This is a brilliant idea! I’ve been testing the kiosk at our groups over the past few weeks and this would be a massive help 🙏

**Comment by alicolville** [comment]
This will be in the next release :)

**Comment by mybestrong** [comment]
Brilliant news Ali ❤️👏👏Be Strong Eat. Move. LiveCICwww.mybestrong.comOn 13 Apr 2023, at 15:42, Ali Colville ***@***.***> wrote:﻿
Closed #462 as completed.
