### ISSUE TITLE
[wt-start-weight] for custom fields

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#467]
to be able to use [wt-start-weight], [wt-previous-weight], etc.. for custom fields could be very beneficial? For example, I could use [wt-previous-waist] to show previous measurements compared to the latest.

**Comment by YOPT21** [comment]
Or could there be more possibilities with the custom fields? Have a look at Nutracheck, they open up the possibilities.

**Comment by alicolville** [comment]
Yeah, nice idea. I'll put it on the list :)

**Comment by alicolville** [comment]
The following shortcodes will be in 10.3!

```
[wt-custom-fields-latest slug="cups-of-water-drank-today"]
[wt-custom-fields-previous slug="cups-of-water-drank-today"]
[wt-custom-fields-oldest slug="cups-of-water-drank-today"]
```

**Comment by YOPT21** [comment]
This is amazing! Thanks Ali really appreciate itS A HullOn 29 Sept 2022 20:20, Ali Colville ***@***.***> wrote:
The following shortcodes will be in 10.3!
[wt-custom-fields-latest slug="cups-of-water-drank-today"]
[wt-custom-fields-previous slug="cups-of-water-drank-today"]
[wt-custom-fields-oldest slug="cups-of-water-drank-today"]
