### ISSUE TITLE
Ability to use fields from Wordpress User

### ISSUE THREAD

**Issue by adclaran** [alicolville/Weight-Tracker#470]
Many websites have extended WP User profiles with new fields. For diet/health websites, the User has been already extended with fields like gender, age group, height or so. 
I think an "integration" with the  WordPress User would be at least beneficial.

**Comment by YOPT21** [comment]
Love this idea

**Comment by alicolville** [comment]
What is a user case for this? Can you explain how you'd like to use it a little more?
