### ISSUE TITLE
New Custom Field: Link

### ISSUE THREAD

**Issue by adclaran** [alicolville/Weight-Tracker#472]
I think having link as custom field would be beneficial. Anyway, I don't see any possible problem. Admins can handle spams by other means, or simply don't use them.
That would OPEN the weight track to a lot of possibilities, connections with other things. Users can 'integrate' their weight track with some "blog posts", for example, talking in details about their successes.

**Comment by alicolville** [comment]
Hi,

So have the ability for a user to just enter a URL into a custom field when submitting an entry?

Cheers,

Ali

**Comment by alicolville** [comment]
Afraid I don't think the demand is there for this.
