### ISSUE TITLE
Beta Observations

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#478]
Ali!

Noticed a couple of issues at [this link](https://mybestrong.com/my-weight/)

disable-theme-css=true
show-delete-data="false
enable-week-ranges=true

All don't seem to work

Love you xx

**Comment by alicolville** [comment]
The following two have been fixed in the 10.2 (to be released soon):

```
show-delete-data=false
enable-week-ranges=true
```
"disable-theme-css' only removes an additional style sheet "uikit-theme.css" which has some extra styles I've put in to make [wt-beta] look a little more uniformed. What are you not seeing?

**Comment by mybestrong** [comment]
Hi Ali,

Im not seeing my standard buttons - its on the home page at www.mybestrong.com

**Comment by alicolville** [comment]
I'm not sure what you mean? Also thought you disabled the beta?

**Comment by mybestrong** [comment]
Hi Ali,

 

No, I love it so its live 😊

 

https://mybestrong.com/my-weight/

 

Have a look and see if it’s as expected x

 

 

 

Rick Wilson

 

Be  Strong

Eat. Move. Live CIC

 

www.mybestrong.com

**Comment by alicolville** [comment]
Ah, ok. I'll have a look for you.

It maybe the CSS class is removed. Can you send me a link to where the buttons look correct and I'll compare.

**Comment by mybestrong** [comment]
Hi Ali,

 

My standard buttons are at www.mybestrong.com <http://www.mybestrong.com> 

 

xx

 

 

 

Rick Wilson

 

Be  Strong

Eat. Move. Live CIC

 

www.mybestrong.com

**Comment by alicolville** [comment]
Going to close this one. The button issue is more because your buttons are coded differently. I thought I had removed certain CSS classes but I haven't. I think you just need some custom CSS to style my buttons to suit.
