### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#482]
Is there any possibilities of opening more options for the rewards? i.e X amount of inputs, X amount of time using the plugin etc?

**Comment by alicolville** [comment]
Yeah, something that could be done too. It's just about getting time I'm afraid!

**Comment by YOPT21** [comment]
Fully understand. You have a few of us here keeping ya on your toes 🙈 sorry about that!

**Comment by sbservices** [comment]
I'd like to add a comment regarding this same enhancement - as currently there is no ability to specify a most important award - Their weight GOAL!! Not suggesting flashing banners and confetti or anything here, but to be able to add an award for reaching Goal weight would be great.

**Comment by YOPT21** [comment]
Any potential future plans for this one?

**Comment by alicolville** [comment]
Not at the moment, but yes, all of them could be done and make sense to do

**Comment by YOPT21** [comment]
👍🏼

**Comment by alicolville** [comment]
Closing this ticket as too generic - I have however added "Met target weight" in 10.4.
 For other award suggestions, please open new issues for each.

**Comment by sbservices** [comment]
yes, I think this is what you have done with adding award for meeting goals. So no probs.
