### ISSUE TITLE
Blank Page Content / Data Issue

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#483]
Hi Ali

This is the Blank Page Content / Users seeing other users weight data instead of their own

[19-Aug-2022 10:58:36 UTC] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/html/wp-content/plugins/weight-loss-tracker/pro-features/plus/bmr.php:85

User affected by blank page

https://mybestrong.com/wp-admin/user-edit.php?user_id=1275

User affected by seeing wrong target weight (this is still there with litespeed cache off)

https://mybestrong.com/wp-admin/user-edit.php?user_id=1275

![image](https://user-images.githubusercontent.com/44278135/185628487-4d02cbb1-bcca-4eed-880f-78e354e268c5.png)

Love you xx

**Comment by alicolville** [comment]
Fixed in 10.2

**Comment by mybestrong** [comment]
You legend x

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com
