### ISSUE TITLE
Kiosk Add Weight Issue

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#485]
Hi Ali

On the add weight entry tab on the brilliant kiosk shortcode it lists every single custom field on my site. As the majority are required fields I cant add a new weight for a user - see screenshot..

[wt-kiosk hide-custom-fields-form=true]

![image](https://user-images.githubusercontent.com/44278135/185932339-359d20dd-4da4-445d-b1a0-9984f64cbf6f.png)

Love you x

**Comment by alicolville** [comment]
Fixed in 10.2.1.
