### ISSUE TITLE
Kiosk Suggestion For Group Totals

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#487]
Ali,

I love the group totals for the day in the kiosk! Is there any chance of having an option for 'all groups'? I'm certain it would be really useful - at least for us it would be :)

![image](https://user-images.githubusercontent.com/44278135/185950461-6892124f-3796-4bea-a8c0-729888465324.png)

**Comment by sbservices** [comment]
Yes, I agree.  And maybe even a date option to view previous class reports.

**Comment by alicolville** [comment]
Will be in the next release.

**Comment by mybestrong** [comment]
That’s brilliant Ali 👏👏👏👏

Be Strong 
Eat. Move. Live
CIC
www.mybestrong.com

**Comment by sbservices** [comment]
yeay!
