### ISSUE TITLE
Notes per page

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#490]
Using the notes-per-page shortcode has seemed to stopped working since update. I have 1 note per page to view, then using the html I create a workout record of their current session. Since I've updated the plugin, this no longer works? Instead it shows at least 3 of the notes per page.

**Comment by alicolville** [comment]
Ah, could you share the shortcode (and arguments) you're using for rendering notes. I'll see if I can debug.

**Comment by YOPT21** [comment]
Hey, sorry for the late reply. Sure thing.

[wt-notes message-no-data="There are currently no notes" notes-per-page=1]

**Comment by alicolville** [comment]
Fixes going out now in 10.2.2. Thanks!
