### ISSUE TITLE
Email notifications to encourage user engagement

### ISSUE THREAD

**Issue by lowcarbclub** [alicolville/Weight-Tracker#493]
We run a membership site in which we offer weight tracker features as one benefit of the membership. 

I'm struggling with the ability to send emails in bulk to members who are not engaging. What I would like is an email to go out every day to users who have not taken action on certain items which would help them, such as logging their weight or even setting up their user preferences as an initial action. 

I have seen issue #479 asking for integration with mail poet in which you have indicated there is no integration, but what is the interim solution? How else can we surface the user data besides manually exporting it? Exporting data does not necessarily solve the problem as the data being exported is only for users who have taken action, it doesn't include user id's for users who have not taken action.

Is there any out of the box solutions for this or does it require custom development?

**Comment by alicolville** [comment]
Hi there,

Thanks for getting in touch.

Yes, I'm afraid there is no real way to do this and would need either custom development or for it to be included in a future release (although this would have to be prioritised amongst other features).

Cheers,

Al

**Comment by lowcarbclub** [comment]
Thanks for the feedback, much appreciated.
