### ISSUE TITLE
New Notes Not Showing Up Frontend

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#495]
When I am leaving new notes for clients and clicking on 'visible to user' it is not showing up?

**Comment by YOPT21** [comment]
As an update, when you go into the backend and view the notes left for the user, where it normally says (Visible via [notes]), the new notes do not have this even though I clicked for them to see the note I left.

**Comment by alicolville** [comment]
Oh, sorry to hear that - I'll try and find the issue tonight

**Comment by YOPT21** [comment]
Many Thanks Ali

**Comment by alicolville** [comment]
Fixed in 10.2.3 (going out shortly)
