### ISSUE TITLE
Name across top of Kiosk

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#500]
During live usage (pressure environment), it is easy to accidentally not change the user before clicking on the Plus icon to add a new weight.  This has resulted in a lot of incorrect entries.  The easiest fix for this would be to have the 'name-and-email' box displayed above all tabs.  I managed to add it to a few of the other tabs with shortcodes, but I couldn't add it to the most important one which was the 'Add-Edit' tab.  Please could you add the option to be able to add boxes here too with shortcodes. Thanks.

**Comment by alicolville** [comment]
This has been added in 10.2.8
