### ISSUE TITLE
Previous Weight Issue

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#501]
When a person is on the scales and before the new weight is entered, the coach is looking at the 'previous weight' to see what the person was last weigh in (usually the week before).  However, when you load the screen for the member, the previous weight shows the weight prior to the last entry, so when they are standing there this week before a new weight is entered, the coach thinks that this is displaying what was last their weight and doing a quick calc in their head whilst waiting for the next screen to load and because she is calculating it in her head (which is just something you do when you're standing weighing people in a 30-60 second window and sometimes the computer has to catch up with you!), she is telling the member an incorrect loss or gain.

Here is an example to explain step by step:-

So today is 12th Sept and the member is standing on the scales in front of me and as a coach I'm looking at this screen before adding a new weight for today:-
https://snipboard.io/Yt6cQ2.jpg
And it looks like my last weight was 11st 8.75lb on 30/8/2022

However, this member attended on the 6th Sept (but as the coach, I don't know this right away).
So lets say the scales are saying 11st 7lb today 12/8/2022
I would be advising that member they are down 1.25lb this week, when in actual fact they are down 1lb from their last weight entry on the 6/9/2022.
See screenshot showing both 30/8/2022 and 6/9/2022:-
https://snipboard.io/NjSULt.jpg

Then I've clicked the 'add-edit' tab to put the new weight in and updated it as normal and all the green boxes appear and everything is showing as normal.

Is it possible to show the 'previous weight' **on-load** screen rather than **on-update**?  But after update show 'previous-weight' entry as being the one before today.

Thanks

**Comment by alicolville** [comment]
I think I get it, but instead of previous-weight, could you not use latest-weight? That will show the latest weight entered in the system for the user?

**Comment by sbservices** [comment]
Yes I've done that for now, but after they then enter the new weight for that day, the 'latest-weight' shows today's result instead of last weeks.  I could put 'previous-weight' in the green section so they have both.
