### ISSUE TITLE
Barcode Scanning of a member instead of typing in search

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#503]
On the kiosk screen where the current search box is, it would be a great enhancement if a member presents a membership card with a barcode on it for scanning as quick result.
Using WooCommerce Point of Sale & WooCommerce Memberships a User already has a 'Barcode' membership number assigned that could be used with the option to use an advanced custom field if the Weight Tracker customer doesn't use Point of Sale or Memberships.

**Comment by alicolville** [comment]
This is potentially something we could look into adding, but I'm afraid it maybe custom work as I feel the majority wouldn't benefit from it.

**Comment by YOPT21** [comment]
If we could add the barcode to the customer profile would allow a link to membership options. For example, Boomarangme creates a user barcode on sign-up, which allows the owner/PT to scan the client in and add awards. This would be very beneficial but I believe the amount of work involved would swing more towards a custom piece of work tho.

**Comment by sbservices** [comment]
Both clients have been using the weight tracker kiosk now for a few weeks and the one thing they have said is slowing them down checking the people in, is having to type in a name i.e. Mary and then scroll down a list of Mary's to find the correct one and sometimes when they make a selection on the tablet it can jump to the wrong selection and they have to clear the selection and start again (we don't know why at the moment as we can't reproduce the issue).  They have both agreed that the simple solution would be to use a bar code scanner to find the member quickly and immediately without having to scroll through a list.  They both have over 600 members and there are a lot of Mary's in Ireland!!

**Comment by YOPT21** [comment]
Can you search by first and last name on the system? I'm not at that big enough scale to notice on my side.

**Comment by YOPT21** [comment]
On a second note, the system fails to find my user after typing first and last name? I'm guessing First name or user name search only?

**Comment by sbservices** [comment]
Yes, this is the problem, you wouldn't know everyone's usernames, and you can only enter a firstname and then have to scroll down a list of people with the same first name.  So if each member had a unique number on a membership card that can be either  searched upon or a barcode scanner to pull up the correct person instantly would be a massive improvement.  My clients are worried about the speed of processing all of the January flood of members that they would expect.  From experience I'd say they will have between 50 and 100 through the door in an hour.  Those seconds spent searching for the member might not seem much, but when you're processing that many people at that speed, the searching and scrolling process isn't very slick.

**Comment by YOPT21** [comment]
A tie in with Boomerangme would be useful??

**Comment by YOPT21** [comment]
https://boomerangmeeng.docs.apiary.io/# 

Thoughts?

**Comment by alicolville** [comment]
I'm not against incorporating it, it's just something like this is technically challenging and a big commitment in time I'm afraid.

I do agree it make senses to look at.

**Comment by YOPT21** [comment]
Totally understand that. Could the search fields include last name searches?

**Comment by sbservices** [comment]
Yes, I understand it would be too.  Would it be of any help to look at the code used in the WooCommerce Point of Sale plugin?  Wondering if there is code there that has potential of being used if they are using a piece of open source?  It might be their own code I don't know.  I don't know enough on php to know what I'm looking at!! LOL

**Comment by alicolville** [comment]
Can you raise another ticket for the search - that said, I'm using the standard WP search under the hood and that's pretty pants.

**Comment by alicolville** [comment]
I could look into WooCommerce, again, getting time, to be fair, don't have many asking for barcode integration, so been focusing on the other tickets which have more demand...

**Comment by sbservices** [comment]
Thanks Ali.  Yes will do.  I'm just looking online to see if any wordpress plugins and found this

https://www.datasymbol.com/faqs/barcode-reader-sdk-technical-questions.html

Am I right in thinking that at Question 10 where it says about integrating with any of your current wordpress plugins, that this could be used by someone like yourself with the right knowledge to integrate it?  I've not a clue, so I apologise if this is a silly question!!

And my 2 clients would be interested to do as a private job if nobody else is needing this. As it would clearly improve their workflow.

**Comment by alicolville** [comment]
This looks like a better option to me: https://websdk.scandit.com/
