### ISSUE TITLE
The Awards Flashing up on Screen isn't working

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#505]
The awards that used to flash as a message across the top of the kiosk screen are not working after plugin update.

**Comment by alicolville** [comment]
Are you sure? The plugin update only removed some text from the help page.

Any examples?

**Comment by sbservices** [comment]
https://www.awesomescreenshot.com/video/11210296?key=8381b3f909831a0b2a24bcf08a8d0a64

I updated from the 10.2.beta to current version.

**Comment by alicolville** [comment]
Sorry for the delay in replying! Either missed the GitHub notification or it didn't appear!

So the award is being assigned, however the notification isn't. Let me see if I can reproduce over the weekend for you. :)

**Comment by alicolville** [comment]
I've managed to fix this. It will be released shortly in 10.2.7 :)
