### ISSUE TITLE
[wt-kiosk] limit users search

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#506]
Is there a way to limit the users the admin can search for? For example, I would have different group types (boxers, weight loss, etc..) I would only want admin 1 to be able to search for the group Boxers, while admin 2 only access the Weight Loss group.

**Comment by alicolville** [comment]
I'm afraid, at the moment, there isn't.

**Comment by YOPT21** [comment]
Ok no worries. Thanks for the reply :)

**Comment by alicolville** [comment]
One way I could potentially do this is to get the group for the logged-in user, and only allow that user to search within the user group they are assigned to. 

If they don't have a group, then they can search everyone?

**Comment by YOPT21** [comment]
That idea would work perfectly for me and what I need.
