### ISSUE TITLE
[wt-beta] swipe

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#507]
I have noticed that when you swipe across to the other sections, the top bar misses the next one and jumps to the next one to that, but the pages are correct.

https://user-images.githubusercontent.com/82499071/192007325-774bfb85-44cb-43f3-91e6-28a686939d07.mp4

**Comment by YOPT21** [comment]
I have just notices that it blends the two sections together.
![Screenshot_20220923-172931_Chrome](https://user-images.githubusercontent.com/82499071/192008766-2a214fd7-19fd-44d5-8fee-4d144b8d4b65.jpg)

**Comment by alicolville** [comment]
I'm not sure I'm quite getting the issue? 

I didn't expect users to be able to swipe but just click on each? What device are you using?

**Comment by YOPT21** [comment]
I am using the system via an android device, which alloys a swipable action.

**Comment by sbservices** [comment]
I have had a report similar to this on tablet view on kiosk.  Whereby when searching for a name and the dropdown box appears, when you are scrolling to find the member and you go to select on screen the dropdown item you want, it jumps and can end up selecting the wrong person.  I have been working with the customer to establish more details on this, and we may have narrowed it down to either the Chrome browser on tablet or the fact its a Chromebook.  The customer is going to test using Firefox.  It didn't see to happen with Opera browser but she didn't like the sidebar that Opera browser has, but she is doing further testing this week.  Could be a related issue.

**Comment by alicolville** [comment]
Could you raise a separate issue for that if you can reproduce @sbservices ? Keeps things simple to track.

**Comment by sbservices** [comment]
will do if I can reproduce the error.  This is why I've not reported it separately just yet!  Just thinking if @YOPT21 was able to test the theory of browser type being an issue, it might help with the investigation.

**Comment by YOPT21** [comment]
I will have another look on other devices later tonight. Will post updates.
