### ISSUE TITLE
[wt-group-view-as-table] auto reconise group

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#510]
Can there be a way when using the shortcode [wt-group-view-as-table] to be able to show the group data for the user's group automatically?

**Comment by alicolville** [comment]
I'll add in this in 10.3.

So want the view to default to their current group.

**Comment by YOPT21** [comment]
Yes please :)

**Comment by alicolville** [comment]
Done. This will be in 10.3
