### ISSUE TITLE
Flag up BMI lower than 18 with a warning or in Red/Flashing

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#512]
Request to have a base line for weight to flag BMI lower than 18 (its rare but it would be good to have) I’m guessing this would be similar to calculating target weight BMI 25.

**Comment by alicolville** [comment]
I'll put this as a maybe. 

Where would you want this to appear? It may make more sense for me to extend [[wt-if]](https://docs.yeken.uk/shortcodes/wt-if.html) to allow comparisons.

**Comment by sbservices** [comment]
Sorry, I should have said for it to appear on the kiosk for the coach so she can advise and also for a member to view (if they are not going to classes they are doing it themselves online for example), they should be notified somehow that their BMI is below the recommended lower limit of 18.  I'm not sure if there are any legal implications of not advising or warning members/users that they are below their recommended limits?

**Comment by sbservices** [comment]
love the [wt-if] codes - this is a great idea.  I will read these in more detail when I get a chance.

**Comment by YOPT21** [comment]
I love this idea

**Comment by YOPT21** [comment]
@sbservices have you had much joy with the [wt-if] shortcodes? I am struggling to get mine to work.

**Comment by sbservices** [comment]
Hi @YOPT21 . 
I haven't actually tested them yet, sorry.  but thanks for reminding me on this one.  I may test this in a few weeks for something I needed to do.

**Comment by YOPT21** [comment]
Keep me updated @sbservices 👍🏼

**Comment by alicolville** [comment]
The following will be in 10.6:

* New feature: Added the arguments "bmi-alert-if-below" and "bmi-alert-if-above" to [wt] to show an alert if the user's BMI is below or above the specified value.
* New feature: Added the arguments "bmi-alert-if-below" and "bmi-alert-if-above" to [wt-kiosk] to show an alert if the user's BMI is below or above the specified value.
