### ISSUE TITLE
Add Meal on [wt-beta]

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#514]
Under the heart icon of the [wt-beta] shortcode, highlights the clients calorie info. Could there be a button added on this page that allows the user to enter the meal enteries?

**Comment by alicolville** [comment]
Do you mean to add a new tab perhaps for Meal Tracker?

**Comment by YOPT21** [comment]
I originally thought that, but then wondered if it could be incorporated into the heart tab with the calorie information?

**Comment by alicolville** [comment]
I'm not sure there would be enough space there for it (that's if I can even get it to work!)

**Comment by YOPT21** [comment]
Thats a fair point! I do love the calorie break down and so do my clients. Hopefully you can get it to work.

**Comment by alicolville** [comment]
After spending some time investigating this, I'm afraid it's quite a bit of work. If there was more interest in it, then I would probably consider doing it. But for now, I'm afraid, I'm going to mark this as closed.
