### ISSUE TITLE
Kiosk Search - Allow searching by fullname and surname

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#515]
Currently, kiosk only allows search by firstname and a list of Mary's is long to scroll down! If this could be updated to allow search on fullname and surname this would be most helpful. Thanks.

**Comment by alicolville** [comment]
I think this has been resolved by the following code:

https://github.com/alicolville/Weight-Tracker/blob/57bf8e7268c3aa9d2e5f12d35de50abdb3dc7987/includes/functions.php#L1679-L1700
