### ISSUE TITLE
Custom Tabs for [wt-beta]

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#516]
Is it possible to leave the option to create custom tabs for above the info of [wt-beta]? Allowing us to personalize the end-user experience more? For example, I would add a tab for body measurements, where I could use my custom fields to view under this heading.

**Comment by alicolville** [comment]
I'm afraid, at the moment, no. But something I could look into adding.

**Comment by YOPT21** [comment]
No worries. Cheers 😀
