### ISSUE TITLE
[wt-custom-fields-latest]

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#519]
Is there away of including [wt-custom-fields-latest] and [wt-custom-fields-previous] on the [wt] shortcode pages under home and history?

**Comment by alicolville** [comment]
Ah, as a box?

**Comment by YOPT21** [comment]
Yeah exactly

**Comment by alicolville** [comment]
Getting there... 

![Image](https://github.com/alicolville/Weight-Tracker/assets/10127199/e457979f-b8d4-4549-94ee-fa88265c8949)

**Comment by YOPT21** [comment]
Looking good

**Comment by alicolville** [comment]
Going out now.

**Comment by alicolville** [comment]
Apologies! Will be in 10.8
