### ISSUE TITLE
Latest Weight Difference

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#523]
Ali,

Getting an odd return for the difference on the latest weight when compared with the previous weight. It only seems to be happening for the one user: -

https://mybestrong.com/wp-admin/user-edit.php?user_id=2601

![julie mills](https://user-images.githubusercontent.com/44278135/196410692-5a289893-05ef-4076-921d-da5b00c1e3f7.png)

This is the page: -

https://mybestrong.com/home/dashboard/weight-tracker/

**Comment by alicolville** [comment]
Fixed in 10.3.4
