### ISSUE TITLE
Won't load fully

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#524]
I don't know if anyone else is having the same issue, however I've noticed since the update that any page that I have the plugin on either freezes unexpectedly or jusy to refuse to load at all.

**Comment by alicolville** [comment]
Oh strange.

Able to send me some links and login details?

**Comment by YOPT21** [comment]
Ill set you up a login and email you the details across

**Comment by YOPT21** [comment]
You now have access (should recieve an email). The link is https://youronlinepersonaltrainer.co.uk/aug-little-test-page/

**Comment by alicolville** [comment]
I've had no other reports... have you installed anything new? I've seeing lots of errors in your console
<img width="875" alt="image" src="https://user-images.githubusercontent.com/10127199/197025163-849a65d7-0e09-49f4-a642-5d3908aa35f0.png">

**Comment by YOPT21** [comment]
Looks like my spam talk, just need to sort out the license key. This was reintroduced last night, so after the issues Iv been getting. Looks like your [wt] works perfectly fine. Might have to just scrap my custom fields for now.

**Comment by alicolville** [comment]
So not a WT issue?

**Comment by YOPT21** [comment]
Appears not to be. Talking to my developer now. Thanks for your help.
