### ISSUE TITLE
Disable CSS Not Working

### ISSUE THREAD

**Issue by shakethatweight-simon** [alicolville/Weight-Tracker#528]
![image](https://user-images.githubusercontent.com/62300999/198260592-7d556495-f058-4994-86b6-178b67c63b16.png)
![image](https://user-images.githubusercontent.com/62300999/198260608-db2c37e3-4a2d-4e59-b337-7bf70f6d1e23.png)

We've tried to disable the CSS, but it's had no effect on the styling. The CSS you are using modifies too many basic styles, e.g. font color/weight/style, it looks nothing like the rest of the site.

**Comment by alicolville** [comment]
Could you try this:

[wt disable-main-font=true]
[wt disable-theme-css=true]

(more here: https://docs.yeken.uk/shortcodes/wt.html)

**Comment by shakethatweight-simon** [comment]
@alicolville  Any other suggestions to remove the styling that is being forced onto this extension?

**Comment by alicolville** [comment]
Have you got an example?

The majority of my CSS is prefixed.

**Comment by shakethatweight-simon** [comment]
@alicolville See original message, you are overriding the font family already defined on the site. I just want to disable the CSS from your extension so buttons, headings etc match the rest of the site. I've tried to disable CSS from the plugin settings and via the shortcode, neither option is having any effect and still results in your CSS being loaded.

**Comment by alicolville** [comment]
Yes, but have you got an example I could login and look at?

**Comment by shakethatweight-simon** [comment]
@alicolville I've sent new user credentials to your email address shown on your Github account, you can use that to login to the site. I'd prefer not to mention the website address and name in public.

**Comment by alicolville** [comment]
Thanks, got in and can see the following code is still be embedded inline:

```


<style id='yk-uikit-inline-css'>
--
  | @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap');
  |  
  | .ws-ls-tracker, .ws-ls-tracker-force-font *, .ws-ls-tracker *, .ykuk-modal-dialog *, .ykuk-notification *, .ykuk-table *   {
  | font-family: "Roboto Mono", monospace !important;
  | }
  | </style>


```
This implies the `disable-main-font` argument hasn't been set to true. Can you confirm the exact shortcode usage you have placed on that page?

**Comment by shakethatweight-simon** [comment]
Lot has happened since this, it is now working as expected, not sure what the change was.
