### ISSUE TITLE
Stones??? WTH is that

### ISSUE THREAD

**Issue by CryptoRPG-World** [alicolville/Weight-Tracker#532]
In the USA there is no one that knows how much a stone weighs. problem is it is a required field in the calculator for the weight tracker. how do i make it non required or removed from the imperial side of calculations

**Comment by alicolville** [comment]
As discussed via email, I'll look at add pounds only in a future release.

As someone based in Scotland, a lot of people do know what a Stone is (14lb).

**Comment by CryptoRPG-World** [comment]
Pounds is already there, just need to remove stones. There is even a feature to use pounds or stones and pound but it is not working.

**Comment by alicolville** [comment]
Yes, I get that - but the code still needs to be changed to calculate and not include Stones. It's not a 5 minute job.

**Comment by alicolville** [comment]
Will be in 10.3.2

**Comment by CryptoRPG-World** [comment]
Thank you.
