### ISSUE TITLE
Customer ID shown on Kiosk Screen

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#534]
Is there a shortcode to display customer ID number in one of the boxes in the kiosk?  I can't see it in the shortcodes. Thanks

**Comment by YOPT21** [comment]
Are you using wordpress/elementor at all?

**Comment by sbservices** [comment]
Yes, Elementor on Wordpress @YOPT21

**Comment by YOPT21** [comment]
Elementor has it own built in, if you want to add it into the page?

**Comment by sbservices** [comment]
I am not sure how to do this?  I wish to display the customers ID number after barcode scanning the customer.  What would I use on Elementor to display the Customer ID please? thanks.

**Comment by YOPT21** [comment]
Iv attached screenshots. But elementor has a function to change text to user info which you can select ID. 
![Screenshot_20221201_192306](https://user-images.githubusercontent.com/82499071/205141791-e7338f11-6322-4f2f-bf81-8312ed699760.jpg)
![Screenshot_20221201-192329_Chrome](https://user-images.githubusercontent.com/82499071/205141802-0cd43d7c-9b28-484a-a2a7-a2b9d2d6a682.jpg)
![Screenshot_20221201_192350](https://user-images.githubusercontent.com/82499071/205141808-06428fba-c065-4fd4-b7f8-5986b1b9ab74.jpg)

**Comment by YOPT21** [comment]
You will have to scroll down a little bit after clicking the first icon (pic 1) to reach 'User Info'

**Comment by sbservices** [comment]
Thanks for that.  
This only shows the ID number of the trainer/coach that is logged in, not the customers ID number unfortunately.
I am looking to include ID number somewhere on here to see customer ID after loading the data.  We can then print a barcode label there and then instead of going home to look up the data in the wordpress back office.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/101115016/205155500-b42119bf-6c3f-4186-bd7e-a28e55b38033.png">

**Comment by YOPT21** [comment]
Ah, sorry about that. Maybe it is something @alicolville could add in as a section like, name, dob, etc..? 
Hope it gets sorted for you soon

**Comment by sbservices** [comment]
thanks @YOPT21 , yes, the information is there in the background, just need a shortcode adding for it like the DOB, name, height, etc..

**Comment by sbservices** [comment]
Hi @alicolville , could you let me know if this is can be added thanks?  And if so, when do you think it could be done?  Or is it something I could do myself?  I can't find a shortcode for Users ID that's all.

**Comment by alicolville** [comment]
A new box, "user-id" will be added in 10.3.3.
