### ISSUE TITLE
[custom-fields-...] error

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#535]
Everytime I use the shortcode [custom-fields-...] it throws up a critical error on my frontend page.

**Comment by YOPT21** [comment]
![Screenshot_20221207-111736_Gmail](https://user-images.githubusercontent.com/82499071/206165704-751f5cde-2d58-4b09-9e3f-3d154eca5b47.jpg)

**Comment by YOPT21** [comment]
I have worked out that it is only the [wt-custom-field-oldest] that throws up the error. The others seem to work.

**Comment by alicolville** [comment]
Could you provide more information please e.g.

- Type of field
-  If the field has a value etc?

I'll add some additional error handling in 10.3.3 which may help.

**Comment by YOPT21** [comment]
So this is a number field. I like to track my client's measurements as well as their weight. So I made custom fields for this. However when I use the custom fields (latest, oldest, etc..) they keep throwing my WordPress site into an error.

**Comment by alicolville** [comment]
Could you send me the shortcode and how you're using it?

Could you also screen shot the custom field settings for me? I can't reproduce it :(

**Comment by YOPT21** [comment]
I'll send this over once I am back home. So the accumulate shortcode works for custom fields.

**Comment by YOPT21** [comment]
[wt-custom-fields-oldest slug="chest"]
![Screenshot 2022-12-30 15 19 40](https://user-images.githubusercontent.com/82499071/210085992-66136cef-3ac4-4f9a-9316-1a92d80b9ee4.png)

**Comment by YOPT21** [comment]
unless there is a way that you can either add body measurements, or just hip and waist, the same way you have the weight? therefore when they update their weight, they could also add their measurements.

**Comment by YOPT21** [comment]
Incredible!! Your top notch. Thanks Ali

**Comment by YOPT21** [comment]
This is the one @alicolville

**Comment by YOPT21** [comment]
It seems to be this one once again

**Comment by YOPT21** [comment]
@alicolville

**Comment by alicolville** [comment]
I'm really struggling to reproduce this one @YOPT21 .

Do you have any more detailed examples? Error you're seeing, shortcode used, etc?

**Comment by YOPT21** [comment]
Every time I am using the [wt-custom-field....] it throws up the error. I can fix the error when I cache my site, but as soon as it loads again it comes up with the same error. I will have to wait for a bit before buying a licence again, but as soon as I do, I'll reproduce and let you know

**Comment by alicolville** [comment]
Presume you have the latest version installed?

How do you cache it? Using page caching?

Would you be able to screenshot the meta field settings and the shortcode you use? It would help me potentially reproduce the issue.
