### ISSUE TITLE
Activity & Fitness Tracking Challenge

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#536]
We would like to use a custom field that allows customers to track their activity for the day.  Choosing from a dropdown list of common activities or 'other', maybe an intensity level and a duration in minutes.

But then for admin to set a 'Challenge' to show who completed the most minutes of exercise by their Group for a date range.  A bit like the Challenge that allows admins to see how many days they tracked weight or meals for a challenge.  

Is there a way we could do this with creating a custom field and exporting data maybe?

**Comment by sbservices** [comment]
As a side thought, there doesn't seem to be any basic fitness tracking wordpress plugins out there, none that have been kept up to date anyway.  Wondering if adding 'Activity Fitness Tracker' to your collection could be useful and allowing people to connect their Fitbit or Samsung Health to pull in basic data such as Stepcount, miles walked and exercise logs into the users profile/account?

**Comment by alicolville** [comment]
I need to start a Kickstarter page - I get this request often :)

**Comment by YOPT21** [comment]
There seem possibilities of linking with strava, google fit, etc with api's, but that is way over my head. If there is something you can build for this feature, that will be worth adding to my yeken collection ;)

**Comment by alicolville** [comment]
Thanks folks, I'm quite keen on this, but it's probably quite a big project that I'm not sure I have time for (over others).

Will close here as not an issue for WT. :)
