### ISSUE TITLE
[wt-if] [else]

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#537]
More of a how do I than an issue.. 
Everytime I use the [else] clause within the [wt-if] it never works? It just shows as [else] blah blah blah. Iv copied and pasted from the shortcode page also. Any help??

**Comment by alicolville** [comment]
Can you show me the code you are using? Seems to work here OK :)

**Comment by YOPT21** [comment]
I tried 
[wt-if field="weight,height"]
	Thank you - we can now calculate your BMI!
[else]
	Please add a weight entry as well as your height.
[/wt-if]

but the [else] blah blah, shows up also.

**Comment by alicolville** [comment]
Strange! Seems fine for me. Is the [else] as seen? The square brackets haven't been replace with HTML encoded characters etc?

**Comment by YOPT21** [comment]
I will double check this once I am back home.

**Comment by YOPT21** [comment]
this seems to work now. seems it was replaced with HTML-encoded characters. Thank you

**Comment by YOPT21** [comment]
Fixed by Ali
