### ISSUE TITLE
Can the Barcode Scanner on Kiosk Default to Always On?

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#538]
I was looking at the instructions and using shortcode

kiosk-barcode-scanner-open="lazer"

My understanding is that this would set the barcode scanner to always be on, so that each time you scan a new bar code it would automatically input and search next barcode without having to click the barcode icon button each time.

This is the code we have on the kiosk page

[wt-beta hide-custom-fields-form=true kiosk-mode=true kiosk-barcode-scanner=true kiosk-barcode-scanner-open="lazer" summary-boxes-kiosk="latest-weight,weight-difference-since-previous,previous-weight,bmi,latest-versus-start,calories-lose,calories-maintain,divider,latest-weight,start-weight,target-weight,latest-versus-target,start-bmi,latest-award,aim,divider,name-and-email,gender,age-dob,height,activity-level,group]

Is this what is supposed to happen, or do I have the wrong understanding of what the **kiosk-barcode-scanner-open="lazer"** is supposed to do?

Thanks
Zoe

**Comment by alicolville** [comment]
Yes, you should see this (as I do):
<img width="912" alt="image" src="https://user-images.githubusercontent.com/10127199/209942733-3a91f6b7-eff1-489b-852a-65a985695237.png">
Have you got the latest version of the plugin installed? Can you also change it from [wt-beta] to [wt] please.

**Comment by sbservices** [comment]
Currently have Version 10.3.2-beta4 
I'll schedule a time with client to do an update and let you know.

**Comment by sbservices** [comment]
That's working now, even for me and I don't have a barcode scanner plugged in! Cheers
