### ISSUE TITLE
Shortcodes causing site to crash

### ISSUE THREAD

**Issue by Smartcowmarketing** [alicolville/Weight-Tracker#542]
Hi 
I am running weight tracker on a site with generatepress and elementor and also using member press.
The member press shortcodes work, however the weight tracker ones cause the pages to crash. See error log

[Fri Dec 30 21:54:01.491907 2022] [cgi:error] [pid 25693:tid 140602029094656] [client 212.132.255.134:53375] AH01215: #10 /home/fatfriends/public_html/wp-includes/class-wp-hook.php(308): do_shortcode('[wt]\\n\\n\\n\\n
hi t...'): /domains/f/a/fatfriends.club/public_html/index.php, referer: http://fatfriends.club/wp-admin/post-new.php?post_type=page

**Comment by alicolville** [comment]
Hi there,

Can you confirm what you have in the shortcode section? This looks suspicious to me :)

[wt]\n\n\n\n
hi t...

Ali

**Comment by Smartcowmarketing** [comment]
It was for [wt] .

I have managed to solve it by rolling back a version of php to 7.4 from 8.0

That managed to do the job

Simon Cripps MCIM
T 020 3137 1826 /  M 07954 548 842
[smart-cow-facebook]<http://www.facebook.com/SmartCowMarketing>[Smart-cow-linkedIn]<https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7lC8fmQcbW3fmFbP2B9nMJW7t5XX43M2py4N64QPYvS9QB8W8rldLn56dCSSf82S2fF02?te=W3R5hFj26QkHmW4mKDt23T1kvSW3H6wS-3Fbt5SW3Fbt723zd-HLW4cMm9W4fdgvcW4m7XTX49M_4s4Q2Bh1&si=4661455098740736&pi=38ef7047-ca49-404d-bce2-216ae839c844>[smart-cow-twitter]<twitter.com/smart_cow>
***@***.***<https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7lC8fmQcbW3fmFbP2B9nMJW7t5XX43M2py4N64QPYvS9QB8W8rldLn56dCSSf82S2fF02?te=W3R5hFj4cm2zwW4cMm9W4fFN9fW3_R5ZJ3K9F8zw3NBBqr48S2&si=4661455098740736&pi=38ef7047-ca49-404d-bce2-216ae839c844>

[Book a meeting with me]<https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7lC8fmQcbW3fmFbP2B9nMJW7t5XX43M2py4N64QPYvS9QB8W8rldLn56dCSSf82S2fF02?te=W3R5hFj4cm2zwW3Fdxr349Kv7LW49Kv3b1JzCRvW4cNDSb1JxwY5W1Lw3TN1LDhH8W3T2-TV4ff1FwW24W6zd1Lw2ndW3z8P531-WkBqW3GKl_z1X12lkW3z8NXw1GyxWgW1--ty21V3Mh21X3&si=4661455098740736&pi=38ef7047-ca49-404d-bce2-216ae839c844>   [Hootsuite-Certification-small] <https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7lC8fmQcbW3fmFbP2B9nMJW7t5XX43M2py4N64QPYvS9QB8W8rldLn56dCSSf82S2fF02?te=W3R5hFj4cm2zwW3ZVbTz41pqnrW43X63Z3T3QQ8W3Fbt5S4cNbjtW3zd14k3K2-zfW1Gy-qY4cQJZ6W3zd-gh1L8dPy34kb2&si=4661455098740736&pi=38ef7047-ca49-404d-bce2-216ae839c844>   [constant contact] <https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7lC8fmQcbW3fmFbP2B9nMJW7t5XX43M2py4N64QPYvS9QB8W8rldLn56dCSSf82S2fF02?te=W3R5hFj26QkHmW4mKDsV43TDd8W3zd-f_43TDjyW3Fdr-h43T4NZW41QVMn1JBrCxW2k9cyQ4cMm9Wf4fFN9f04&si=4661455098740736&pi=38ef7047-ca49-404d-bce2-216ae839c844> ***@***.*** ***@***.***  ***@***.*** <https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7lC8fmQcbW3fmFbP2B9nMJW7t5XX43M2py4N64QPYvS9QB8W8rldLn56dCSSf82S2fF02?te=W3R5hFj26QkGZW3F4DJm3___nnW4hCWyF43X00wW43T4NS3K8R9mW3M3BX74fJg0T0&si=4661455098740736&pi=38ef7047-ca49-404d-bce2-216ae839c844>

The email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.  Any review, re: transmission, dissemination, copy or other use of, or taking of any action in reliance upon this information by persons other than the intended recipient is prohibited and may be unlawful.  If you have received this email in error please notify the sender immediately. You should not copy it for any purpose, or disclose the contents to any other person.

Smart Cow accepts no liability for the contents of this message or the consequences of any action taken on the basis of information provided, unless the information is subsequently confirmed in writing by an authorised representative of smart cow marketing.

Smart Cow have taken reasonable precautions to ensure that no viruses are present in this message and cannot accept responsibility for any loss or damage arising from the use of this message.

Smart Cow Marketing is the trading name of Acvita Ltd. Registered Office: Palmerston House, 814 Brighton Rd, Purley CR8 2BR.  Telephone: 020 3137 1826. Registered in England & Wales No: 7039120 /
