### ISSUE TITLE
Keyboard always On screen if Lazer set as default

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#545]
When the default scanner is set to 'Lazer' the keyboard on the tablet is always on after entering a weight, which covers up any weight and customer info.  Are you able to stop the keyboard popping up after adding weight?  Seems that after entering a weight and the screen refreshes back to the main kiosk screen, the cursor goes in to the barcode scanner box awaiting input from keyboard/scanner.

Video clip here showing sequence of events, from searching for customer, bringing up the data, clicking on 'add new weight', and then the screen refreshing back to main screen with customers data (which it should obviously), but then the keyboard overlaying the customers weight info covering up the content.

https://tempclip.com/umYX3KWYyC2Nh8J/watch

Thanks

**Comment by alicolville** [comment]
This is where it gets complicated really. 

Previously you asked for the Barcode scanner to always be ready, which means focusing on that input field (and therefore Android displays the keyboard) when the page loads.

The only real thing we could do, is perhaps not open the scanner upon a form submission  - this would mean though you'd need to press the scan button when wanting to scan another barcode.

**Comment by sbservices** [comment]
thanks @alicolville 
We will experiment with keyboard settings on the device.  Not sure if the one is using a Chromebook or an iPad, I don't think it's android.
