### ISSUE TITLE
Measurements like weight entering

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#547]
Is there away of having an input for measurement tracking like the way we do for weight tracking? Like a simple form to enter new measurements (hip, waist, neck etc..) and to be able to see past enteries also?

**Comment by alicolville** [comment]
Yeah, I think.

You could set the relevant custom fields up and then just use these shortcodes?

https://docs.yeken.uk/shortcodes/wt-custom-fields-form.html

https://docs.yeken.uk/shortcodes/wt-custom-fields-chart.html

https://docs.yeken.uk/shortcodes/wt-custom-fields-table.html

**Comment by YOPT21** [comment]
This is the way I was doing it, unfortunately these still causes the site to crash.

**Comment by YOPT21** [comment]
It's the same ones as the previous ones that you found out.

**Comment by alicolville** [comment]
Ah remind me lol... which shortcode isn't working?

**Comment by YOPT21** [comment]
I tagged you in the original thread

**Comment by alicolville** [comment]
Can you link the ticket here again mate, I'm sorry, I've been really slow at the moment!! Family, new house, etc. I'm hoping to get back on form this month!
