### ISSUE TITLE
Same issue with custom field, latest, previous etc

### ISSUE THREAD

**Issue by YOPT21** [alicolville/Weight-Tracker#548]
![Screenshot_20221207-111736_Gmail](https://user-images.githubusercontent.com/82499071/206165704-751f5cde-2d58-4b09-9e3f-3d154eca5b47.jpg)

_Originally posted by @YOPT21 in https://github.com/alicolville/Weight-Tracker/issues/535#issuecomment-1340821097_

**Comment by YOPT21** [comment]
![Screenshot_20230329_172807_Gmail](https://user-images.githubusercontent.com/82499071/228606441-ff4960c4-f3a7-498d-8f6a-06b0dacbfd5f.jpg)

**Comment by alicolville** [comment]
Just found I forgot to publish my previous fix for this!!!!! Let me see if that helps. (10.3.7)
