### ISSUE TITLE
Deleting Awards

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#549]
If a person enters their weight incorrectly, it generates a heap of awards.  Then you have to delete them all, and then enter the correct weight, where upon it regenerates all of the awards again and sends emails out to the user.

Is it possible to be able to correct the weight and just remove the awards that were generated in error?

**Comment by alicolville** [comment]
Err, not easily as an award is not linked to a weight entry. I'd have to change the system to do that and then remove the awards if the weight entry is deleted.

**Comment by sbservices** [comment]
to have it remove awards if the weight entry is deleted would make sense.  It is very common to enter the wrong weight!!  Members do it themselves as do the coaches weighing them in too.  But its a bigger admin task than it needs to be to clean it back up again.

**Comment by alicolville** [comment]
So potentially if I was able to track what weight entry triggered the awards, if the weight entry is deleted then delete the relevant awards... they will then be added back on when the user adds the new entry.

**Comment by sbservices** [comment]
yes, that is exactly right.

**Comment by alicolville** [comment]
Deployed in 10.5
