### ISSUE TITLE
Green Kiosk Boxes Appear before Weight Entered

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#555]
I have installed the latest Weight Tracker, but I'm noticing the kiosk shows all the Green Box info before entering the weight and it also doesn't seem to be returning back to the (i) information screen after adding customer's preferences and saving them.

**Comment by alicolville** [comment]
Hi Zoe,

I don't think the settings page did redirect did it? :p

As for the green box info, would you mind recording what you mean? I don't think anything I changed would affect that, but you never know!! :)

**Comment by sbservices** [comment]
https://www.awesomescreenshot.com/video/17805314?key=a8147337b642f227f4ffc0f7d722a156

Green boxes are only supposed to appear after inputting todays weight. But they are there immediately upon loading the client info

**Comment by sbservices** [comment]
Also we had it set so that after we enter the preferences, it should automatically go back to the info screen but it stays on the settings page

https://www.awesomescreenshot.com/video/17805397?key=3859a3902241441b937e0a24c016b54a

**Comment by alicolville** [comment]
Ah, the hiding of boxes was done with custom CSS (as not everyone would want to hide it). Do you still have the custom CSS rule?

**Comment by sbservices** [comment]
Ahh yes, I remember now, I will have that on the other websites. Something in the back of my mind was saying that this was something we could do that was just for us, but I couldn’t think of what it was. I’d gone through all the settings and couldn’t find anything to jog my mind on this!

Cheers

**Comment by sbservices** [comment]
How did we make it default back to the Information screen after updating preferences?  Is that another custom script?
