### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by mybestrong** [alicolville/Weight-Tracker#567]
Hi Ali! 

Love you 🥰 

My weight tracker went down with the latest release as I was using beta in the shortcode.

That was easily sorted.

I just noticed that wlt is also not being supported and we need to use wt instead. I have 47 pages using wlt in the shortcode that appear to still be working. How long have I got to update them all?

My hero 🦸‍♀️ 

Rick

**Comment by alicolville** [comment]
That's why you should read the release notes before updating ;)

I guess caching must be keeping it alive right now, I'd change immediately I'm afraid.

One love.

**Comment by mybestrong** [comment]
Cheers Ali - I’ll sort asap. More love ❤️ Be Strong Eat. Move. LiveCICwww.mybestrong.comOn 12 Sep 2023, at 12:29, Ali Colville ***@***.***> wrote:﻿
Closed #567 as completed.
