### ISSUE TITLE
Award Deletions and Low BMI Red Flag Not working

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#568]
I have updated the clients to latest Weight Tracker, but there are 2 updates that I thought were in the latest edition, that I don't think are working.

1) Awards - We thought that if we delete the weight entry that triggered the awards, that the awards would be removed as well, but that doesn't happen, they are still there.
2) Also, if BMI is below 18 was expecting to flag up in red, but I didn't see this too.

I've purged our cache after the updates, but still seems to be not working. Did I need to enable something or should it be automatic?

**Comment by alicolville** [comment]
Hi Zoe, for 1, can you check if you have enabled the setting to delete awards?

![image](https://github.com/alicolville/Weight-Tracker/assets/10127199/900e6a2c-d1e0-4158-ba1e-c35b3887fd16)

Have you included the following arguments on the [wt] shortcode?

```
 "bmi-alert-if-below" and "bmi-alert-if-above" to [wt] 
```

**Comment by sbservices** [comment]
got it thanks a mill.
