### ISSUE TITLE
Edit entry link from wt-table shortcode

### ISSUE THREAD

**Issue by shakethatweight-simon** [alicolville/Weight-Tracker#569]
We have created a weight tracker "dashboard" of our own, using a variety of wt-* shortcodes. When we enabled `enable-add-edit=true` to the `wt-table` shortcode we've noticed the page reloads, and replaces the wt-table with an edit form, but this form is a long way down our page. The edit form has a custom id attribute, is it possible to edit the url in `assets\js\data.footable.js` to include a bookmark to that table id?

I can see the edit url  in the code below, but haven't got as far as tracking down the edit form to work out how you've created that id.
https://github.com/alicolville/Weight-Tracker/blob/master/assets/js/data.footable.js#L104

**Comment by alicolville** [comment]
As in jump to an anchor within the page?

**Comment by shakethatweight-simon** [comment]
@alicolville  Yes, exactly. You already have an id on the edit form which can be used as the anchor, so it's only updating line 104 of the code mentioned before to set the correct link.

**Comment by alicolville** [comment]
This will be out in the next release.
