### ISSUE TITLE
BMR shortcode?

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#575]
Hi, I have searched through the documentation and I can't find how I can add **current BMR** to the Kiosk screen. I can see it is on the Heart Tab, but if you can point me to the shortcode for it please. Sorry to have to ask.

**Comment by alicolville** [comment]
As in?

`[wt-kiosk summary-boxes-kiosk="start-bmr"]`

**Comment by sbservices** [comment]
No, as in this one - the current BMI

![WhatsApp Image 2023-11-27 at 16 26 02_abc830b1](https://github.com/alicolville/Weight-Tracker/assets/101115016/a868be07-6bce-4b58-ae40-fc5b5c727683)

**Comment by alicolville** [comment]
Ah, try "bmr"

**Comment by sbservices** [comment]
nope!!

**Comment by alicolville** [comment]
It's `bmr` in the code base, can show you show me the shortcode you're using?

**Comment by sbservices** [comment]
it is showing now - ignore!  Must have needed the cache clearing or something.
