### ISSUE TITLE
IF statements enhancement

### ISSUE THREAD

**Issue by lbdsgn** [alicolville/Weight-Tracker#584]
I love the idea of the IF statements. 
The way I'd want to use them is with math operators, to be able to provide more nuanced feedback. 
For example: 
IF weight change exceeds -3, then... (message)
ELSE
IF weight change exceeds -2, then... (message)
ELSE
IF weight change exceeds -1 then... (message)
ELSE 
IF weight change exceeds +1.5 then... (message) 
IF Weight change exceeds +0.5 then... (message)
ELSE 
etc

This allows for congratulating or correcting, with different advice for different situations. 

A "message bank" would also be amazing, so that you can rotate through messages for each category of feedback.

**Comment by alicolville** [comment]
Yes, this is something that could potentially be added into a future release :)

**Comment by alicolville** [comment]
I'll add this into the Kanban for scoping out the work involved.

**Comment by alicolville** [comment]
Deployed in 10.17
