### ISSUE TITLE
Latest Weight Box to Show Weight Gain/Loss in lbs (and colour change for loss or gain)

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#585]
Could we add the weight loss or weight gain in lbs as well as being a % for the end users?

![image](https://github.com/alicolville/Weight-Tracker/assets/101115016/61ea9851-1ece-421f-8c63-67d04eb02ebe)

In kiosk mode we can see this figure in lbs and is green if it is a loss and orange if its a gain. I can't remember if its green or orange if it is zero, but if the logic you have in the value on kiosk mode for 'latest weight' box can be adjusted slightly, that would be super.

**Comment by lbdsgn** [comment]
Just don't lose the weight change in %, as percent bodyweight is the more accurate, scientific measure of progress.

**Comment by alicolville** [comment]
Thinking something like this? Or would you prefer it showed one or the other? 
![image](https://github.com/alicolville/Weight-Tracker/assets/10127199/99fd0c67-deac-4bce-a52d-507d83eecfd7)

**Comment by lbdsgn** [comment]
Fantastic!

**Comment by alicolville** [comment]
I think the best I can do is separate labels, one big one can be too big in most instances and won't wrap:

<img width="686" alt="image" src="https://github.com/alicolville/Weight-Tracker/assets/10127199/38ff9a20-bd8e-4575-a360-56317b19a1ef">

**Comment by abdulmominseo** [comment]
My 52-Week Weight Loss Journey Unveiled | Ian Melton's weight loss story
Rating-⭐⭐⭐⭐⭐
[Click full video ](https://youtu.be/P2aNQFrT0yM?si=EJs5XkHPzSwgo1kl)

**Comment by lbdsgn** [comment]
Ah, if space is an issue, then some options are: 
stacking them, as you did here
or a preference/shortcode setting to display weight OR percentage, but not both. Because each coach will have opinions on what they want their clients to see. 

Related to this, from my perspective, the option to have a shortcode square to replace the "Latest vs Target" with a "Start to Latest" with percent change showing. My clients want to display their progress to date, not their distance yet to go.

**Comment by abdulmominseo** [comment]
Delicious & Exciting Diet Foods : Weight Loss Food full video - https://youtu.be/4Kr8gtd2oss?si=1HVNwuBNTKgr4XCL

**Comment by lbdsgn** [comment]
WTH Abdul?

**Comment by sbservices** [comment]
> WTH Abdul?

Hopefully, Ali has reported his spammer ass!

**Comment by alicolville** [comment]
Will be in 10.8

**Comment by sbservices** [comment]
Hi, I've been quiet for a while!! 😁

But I've a query on this subject. 

Point 1 here in this image, since the updates, this box doesn't seem to show like it did before.  Has the new changes supposed to replace this box?

<img width="955" alt="image" src="https://github.com/alicolville/Weight-Tracker/assets/101115016/6e61877a-2b00-40f9-9d0c-39db5f68edf8">

**Comment by alicolville** [comment]
(Above message duplicated in #601)
