### ISSUE TITLE
GDPR Compliance Birthday Emails

### ISSUE THREAD

**Issue by sbservices** [alicolville/Weight-Tracker#602]
When someone requests to unsubscribe from birthday emails, I can't see a way to turn them off at user level. So we'd have to turn them all off or all on.  Could there be something in the wordpress 'users' profile page that allows the Weight Tracker emails to be switched off at user level.

**Comment by sbservices** [comment]
or better still, allow users to unsubscribe in their preference settings. Saves the administrator having to go in and edit it for each user that requests it!

**Comment by alicolville** [comment]
Will be in 10.9
