### ISSUE TITLE
pro version gravityform integration does not create awards?

### ISSUE THREAD

**Issue by beachcalsix** [alicolville/Weight-Tracker#620]
Hello, I purchased the prov version of weight tracker for the awards add on. We also use gravityform integration for when users want to fill out an online journal with fitness goals as an all in one submission. The gravity form integration works great and updates their wlt chart but the awards do not get issued. The user has to submit a future entry in the wlt chart with a future date so that the awards will show up. Is there a way to fix this that I'm not aware of? 

Thanks for the help!

**Comment by alicolville** [comment]
Oh, let me see if I can reproduce and get back to you :)

**Comment by alicolville** [comment]
A fix will be released today in 10.18.1 :)
